service: Zombie

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 512
  timeout: 30
  region: eu-west-1
  profile: default
  role: arn:aws:iam::505939746198:role/service-role/ApiRole

functions:
  authorizer:
    handler: functions/authorize.handler
    name: ${self:service}Authorizer-${opt:stage, self:provider.stage}
    description: Login for aws hackaton

  login:
    handler: functions/login.handler
    name: ${self:service}Login-${opt:stage, self:provider.stage}
    description: Login for aws hackaton
    events:
      - http:
          path: /login
          method: post
          cors:
            origins:
              - '*'
            headers:
              - AuthToken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token

  me:
    handler: functions/me.handler
    name: ${self:service}Me-${opt:stage, self:provider.stage}
    description: Resolving user profile
    events:
      - http:
          path: /me
          method: post
          authorizer:
            name: authorizer
            resultTtlInSeconds: 600
            identitySource: method.request.header.AuthToken
          cors:
            origins:
              - '*'
            headers:
              - AuthToken
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token

package:
  individually: true
  exclude:
    - test/**
    - .git/**
    - .vscode/**
    - .idea/**
    - yarn.lock
    - node_modules/**/README.*
    - node_modules/**/test/**

plugins:
  - serverless-plugin-webpack
